coinginie/users/urls.py
from django.urls import path

from coinginie.users.views import (
    PrivacyPolicyUpdate,
    SubscribePlans,
    UserBankUpdate,
    UserDocUpdate,
    UserUpdateView,
    close_account,
    kyc_verification,
    subscribe,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~subscription/contract/<int:pk>/", view=subscribe, name="subscribe"),
    path("~close/<str:username>/", view=close_account, name="close_account"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~contracts/", view=SubscribePlans.as_view(), name="plans"),
    path("~bank/", view=UserBankUpdate.as_view(), name="account"),
    path("~privacy/", view=PrivacyPolicyUpdate.as_view(), name="privacy"),
    path("~doc/", view=UserDocUpdate.as_view(), name="doc"),
    path("~update/", view=UserUpdateView.as_view(), name="profile"),
    path("~kyc/", view=kyc_verification, name="kyc"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

coinginie/wallet/urls.py
from django.urls import path

from .views import (
    InvestView,
    WithdrawView,
    all_transactions,
    verify_deposit,
    verify_withdraw,
)

app_name = "wallet"
urlpatterns = [
    path("~transactions/", view=all_transactions, name="transactions"),
    path("~invest/confirm/<int:id>/", view=verify_deposit, name="invest_verify"),
    path("~invest/", view=InvestView.as_view(), name="invest"),
    path("~withdraw/confirm/<int:id>/", view=verify_withdraw, name="withdraw_verify"),
    path("~withdraw/", view=WithdrawView.as_view(), name="withdraw"),
]

config/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.flatpages import views as flatpage_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views import defaults as default_views
from django.views.generic import TemplateView
from filebrowser.sites import site as filebrowser

from coinginie.core.views import (
    DashboardTradeView,
    DashboardView,
    MyPasswordChangeView,
    MyPasswordSetView,
)
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("complete-investment/", TemplateView.as_view(template_name="pages/complete.html"), name="comp-inv"),
    path("dashboard/", DashboardView.as_view(),name='dashboard'),
    path("dashboard/MT5/", DashboardTradeView.as_view(),name='dashboard-trade'),

    # Django Admin, use {% url 'admin:index' %}
    # path('jet/', include('jet.urls', namespace='jet')),
    # path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard')),
    path(_("admin/"), include("admin_honeypot.urls", namespace="admin_honeypot")),
    path(_(settings.ADMIN_URL), admin.site.urls),
    path(_(settings.ADMIN_DOC_URL), include("django.contrib.admindocs.urls")),
    path(_(settings.ADMIN_FILEBROWSER_URL), filebrowser.urls),


    # User management
    path("users/", include("coinginie.users.urls", namespace="users")),
    path("wallet/", include("coinginie.wallet.urls", namespace="wallet")),
    path("accounts/", include("allauth.urls")),


    # Your stuff: custom urls includes go here
    path('auth-logout/',TemplateView.as_view(template_name="account/logout-success.html"),name ='pages-logout'),
    path('auth-lockscreen/',TemplateView.as_view(template_name="account/lock-screen.html"),name ='pages_lockscreen'),
    #Custum change password done page redirect
    path('accounts/password/change/', login_required(MyPasswordChangeView.as_view()), name="account_change_password"),
    #Custum set password done page redirect
    path('accounts/password/set/', login_required(MyPasswordSetView.as_view()), name="account_set_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# flatpages
if flatpage_views:
    urlpatterns += [
        path(_("terms/"), flatpage_views.flatpage, {"url":"/terms/"}, name="terms"),
        path(_("cookies/"), flatpage_views.flatpage, {"url":"/cookies/"}, name="cookies"),
        path(_("privacy/"), flatpage_views.flatpage, {"url":"/privacy/"}, name="privacy"),
    ]


# Translation urls
urlpatterns += [
    # path('rosetta/', include('rosetta.urls')),
    path('upload/', include('django_file_form.urls')),
    path('tinymce/', include('tinymce.urls')),
    # Language switcher support urls for django
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += [
    path("sitemap.xml/", sitemap, kwargs={"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

admin.site.site_header = "Dashboard - Ginie Nodes"
admin.site.site_title = "Ginie Nodes DB"
admin.site.index_title = "Ginie Nodes DB"

coinginie/core/models.py
from django.db import models

# Create your models here.

coinginie/wallet/forms.py
from allauth.account.forms import (
    ChangePasswordForm,
    LoginForm,
    ResetPasswordForm,
    ResetPasswordKeyForm,
    SetPasswordForm,
    SignupForm,
)
from crispy_forms.helper import FormHelper
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _

from .models import Deposit, Withdraw

User = get_user_model()


class WithdrawForm(forms.ModelForm):
    class Meta:
        model = Withdraw
        fields = [
            "currency",
            "address",
            "amount",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['currency'].widget = forms.RadioSelect(attrs={'class': 'form-control'})
        self.fields['address'].widget = forms.TextInput(attrs={'class': 'form-control mb-1','placeholder':'Address','id':'autocomplete_input'})
        self.fields['amount'].widget = forms.NumberInput(attrs={'class': 'form-control mb-1','placeholder':'Wallet Address'})

        
class InvestForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = [
            "currency",
            "amount",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['currency'].widget = forms.RadioSelect(attrs={'class': 'form-control'})
        self.fields['amount'].widget = forms.NumberInput(attrs={'class': 'form-control'})

coinginie/contracts/views.py
from django.shortcuts import render

# Create your views here.

coinginie/core/views.py
from allauth.account.views import PasswordChangeView, PasswordSetView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import request
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.base import TemplateView

from coinginie.wallet.models import Transactions


# Create your views here.
class DashboardView(LoginRequiredMixin,View):
    def get(self,request):
        greeting = {}
        greeting['heading'] = "Dashboard" 
        greeting['pageview'] = "Dashboards"
        greeting['transactions'] = Transactions.objects.filter(user=request.user).order_by("-created")[:10]
        greeting['deposits'] = Transactions.objects.filter(user=request.user, type="Invest").order_by("-created")[:10]
        greeting['withdrawals'] = Transactions.objects.filter(user=request.user, type="Withdraw").order_by("-created")[:10]
        return render (request,'dashboard/dashboard-crypto.html',greeting)

class DashboardTradeView(LoginRequiredMixin,View):
    def get(self,request):
        greeting = {}
        greeting['heading'] = "MT5 Trade View" 
        greeting['pageview'] = "MT5 Trade View"
        return render (request,'dashboard/dashboard-trade.html',greeting)

class MyPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy('dashboard')
    
class MyPasswordSetView(LoginRequiredMixin, PasswordSetView):
    success_url = reverse_lazy('dashboard')

coinginie/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from formtools.preview import FormPreview

from coinginie.contracts.models import Contract, Plans, Subscription
from coinginie.users.forms import (
    AccountSettingsForm,
    DocFileForm,
    InvestorForm,
    PrivacyPoliciesForm,
)
from coinginie.users.models import AccountSettings, Investor, PrivacyPolicies
from coinginie.wallet.models import Deposit, Transactions
from coinginie.wallet.tasks import send_admin_mail, send_deposit_mail

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['bankform'] = self.third_form_class(self.request.POST or None, instance=self.request.user.account)
        # context['imageform'] = self.fourth_form_class(self.request.POST or None, self.request.FILES, instance=self.request.user.userprofile)
        context['transactions'] = Transactions.objects.filter(user=self.request.user) 
        context['heading'] = "Profile" 
        context['pageview'] = "Profile"
        return context

user_detail_view = UserDetailView.as_view()

class UserBankUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = AccountSettings
    form_class = AccountSettingsForm
    success_message = "Bank Information successfully updated"

    def get_success_url(self):
        return reverse("users:profile")

    def get_object(self):
        return self.request.user.account

class UserDocUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Investor
    form_class = DocFileForm
    success_message = "Documents successfully updated"

    def get_success_url(self):
        return reverse("users:profile")

    def get_object(self):
        return self.request.user.investor

# def  file_upload(request):
#     if request.method == "POST":
#         doc = request.FILES.get('file')
#         Investor.objects.filter(user=request.user).update(doc=doc)
#         return HttpResponse('')
#     return JsonResponse({'post':'false'})
    
class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Investor
    template_name = "users/profile.html"
    form_class = InvestorForm
    # third_form_class = AccountSettingsForm
    # fourth_form_class = DocFileForm
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user.investor
    
    def form_valid(self, form):
        form.save()
        User.objects.filter(username=self.request.user.username).update(profile_updated=True)   
        return super().form_valid(form)
       
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['bankform'] = self.third_form_class(self.request.POST or None, instance=self.request.user.account)
        # context['docform'] = self.fourth_form_class(self.request.POST or None, self.request.FILES, instance=self.get_object())
        context['heading'] = "Update Profile" 
        context['pageview'] = "Update Profile"
        return context


user_update_view = UserUpdateView.as_view()

@login_required
def kyc_verification(request):
    if request.method == 'POST':
        bankform = AccountSettingsForm(request.POST or None, instance=request.user.account)
        docform = DocFileForm(request.POST or None, request.FILES, instance=request.user.investor)

        if bankform.is_valid() and docform.is_valid():
            bankform.save()
            docform.save()
            
            to_email = request.user.email
            subject = "[GinieNodes] User Verification"
            body = f"""
            Dear {request.user.first_name},
            
            Your request to be verified is being processed.
            
            Please be patient
            
            Yours Truly
            Ginie Nodes
            """
            send_deposit_mail.delay(to_email, subject, body)

# ---------------------------------------------------------------------------

            admin_subject = "[User Verification Request] Admin Notice"
            admin_body = f"""
            {request.user.username} has requested to be verified.
            
            Confirm the information provided.
            
            Then verify them if they meet requirements.
            """
            admins = settings.ADMINS

            send_admin_mail.delay(admins, admin_subject, admin_body)

            # User.objects.filter(username=request.user.username).update(is_verified=True)
            return redirect(request.user.get_absolute_url())
    else:
        bankform = AccountSettingsForm()
        docform = DocFileForm()   
        
            
    return render(request, 'users/kyc.html', {'bankform':bankform,"docform":docform, "heading":"KYC Verification", "pageview":"KYC Verification"})
        
class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class PrivacyPolicyUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = PrivacyPolicies
    template_name = "users/privacy.html"
    form_class = PrivacyPoliciesForm
    success_message = _("Privacy Settings successfully updated")
    
    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user.userprivacypolicy
    
    # def form_valid(self, form):
    #     form.save()
    #     return self.get_success_url()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = "Privacy Settings" 
        context['pageview'] = "Privacy Settings"
        return context


def subscribe(request, pk):
    contract = get_object_or_404(Plans, pk=pk)
    if request.user.subscription:
        Subscription.objects.filter(user=request.user).update(contract=contract)
        return redirect(request.user.get_absolute_url())


class SubscribePlans(LoginRequiredMixin, ListView):
    model = Plans
    template_name = "users/plans.html"
    context_object_name = "objects"
    queryset = Plans.objects.all().order_by('created')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = "Contracts" 
        context['pageview'] = "Contracts"
        return context
    
    
@login_required
def close_account(request, username):
    if not request.user:
        return reverse_lazy("home")
    
    user = get_object_or_404(User, username=username)
    User.objects.filter(username=user.username, is_active=True).update(is_active=False)
    messages.info(request, "Successfully Closed Account")
    return reverse_lazy('home')

coinginie/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />

    <title>{{heading}} | Skote - Admin & Dashboard Template</title>
    
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    {% block css %}
    {% block extra_css %}
    {% endblock %}
    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />
    {% endblock css %}
</head>


<body data-sidebar="dark">
    <!-- Begin page -->
    <div id="layout-wrapper">
        {% block header %}
        {% include 'partials/header.html' %}
        {% endblock %}
        {% block sidebar %}
        {% include 'partials/sidebar.html' %}
        {% endblock %}
        {% comment %} {% block header %}
        {% include 'partials/hori-header.html' %}
        {% endblock %}
        {% block sidebar %}
        {% include 'partials/hori-sidebar.html' %}
        {% endblock %} {% endcomment %}
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">
            <div class="page-content">
                <div class="container-fluid">
                    <!-- start page title -->
                    <div class="row">   
                        <div class="col-12">
                            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                                <h4 class="mb-sm-0 font-size-18">{{heading}}</h4>

                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">{{pageview}}</a></li>
                                        <li class="breadcrumb-item active">{{heading}}</li>
                                    </ol>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->
                    {% block contents %}

                    {% endblock %}
                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->
            {% block footer %}
            {% include 'partials/footer.html' %}
            {% endblock %}
        </div>
        <!-- end main content-->
    </div>
    <!-- END layout-wrapper -->
    {% block Subscribe %}
    {% endblock %} 

    {% block r_sidebar %}
    {% include 'partials/rightsidebar.html' %}
    {% endblock %}

            {% block javascript %}
            <!-- JAVASCRIPT -->
            <script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
            <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
            <script src="{% static 'libs/metismenu/dist/metisMenu.min.js' %}"></script>
            <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
            <script src="{% static 'libs/node-waves/dist/waves.min.js' %}"></script>


            {% block extra_javascript %}
            {% endblock %}

            <script src="{% static 'js/app.js' %}"></script>    
            {% endblock javascript %}

            <script>
                (function(b,i,t,C,O,I,N) {
                  window.addEventListener('load',function() {
                    if(b.getElementById(C))return;
                    I=b.createElement(i),N=b.getElementsByTagName(i)[0];
                    I.src=t;I.id=C;N.parentNode.insertBefore(I, N);
                  },false)
                })(document,'script','https://widgets.bitcoin.com/widget.js','btcwdgt');
            </script>

            {% for message in messages %}
            <script type=text/javascript>
                iziToast.settings({
                    timeout: 9000,
                    position: 'topRight',
                    drag: true,
                    pauseOnHover: true,
                    transitionIn: 'flipInX',
                    transitionOut: 'flipOutX',
                    transitionInMobile: 'fadeInUp',
                    transitionOutMobile: 'fadeOutDown',
                    close: true,
                    balloon: true,
                    progressBar: true,
                    progressBarEasing: 'ease',
                    pauseOnHover: true,
                    icon: 'material-icons',
                    iconText: '{% if message.tags == "info" %}info{% elif message.tags == "success" %}check_circle{% elif message.tags == "warning" %}warning{% else %}priority_high{% endif %}',
                });
                iziToast.{{ message.tags }}({
                    id: '{{ message.tags }}',
                    title: '{{ message.tags|capfirst }}',
                    message: '{{ message }}',
                });
            </script>
            {% endfor %}

        </body>

    </html>

coinginie/templates/partials/css.html
{% load static %}
{% block css%}
    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/iziToast.min.css' %}" rel="stylesheet">
{% endblock%}

coinginie/templates/partials/footer.html
{% load static %}
{% block footer %}
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © GinieNodes.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                A new wave of profit making
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
{% endblock %}

coinginie/templates/partials/javascript.html
{% load static %}
{% block javascript %}
<!-- JAVASCRIPT -->
<script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'libs/metismenu/dist/metisMenu.min.js' %}"></script>
<script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
<script src="{% static 'libs/node-waves/dist/waves.min.js' %}"></script>

<!-- apexcharts -->
<script src="{% static 'libs/apexcharts/dist/apexcharts.min.js' %}"></script>

<!-- dashboard init -->
<script src="{% static 'js/pages/dashboard.init.js' %}"></script>

<!-- App js -->
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/iziToast.min.js' %}"></script>

{% endblock %}

coinginie/templates/partials/rightsidebar.html
{% load static %} {% block r_sidebar %}
    <!-- Right Sidebar -->
    <div class="right-bar">
        <div data-simplebar class="h-100">
            <div class="rightbar-title d-flex align-items-center px-3 py-4">
        
                <h5 class="m-0 me-2">Settings</h5>

                <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                    <i class="mdi mdi-close noti-icon"></i>
                </a>
            </div>

            <!-- Settings -->
            <hr class="mt-0" />
            <h6 class="text-center mb-0">Choose Layouts</h6>

            <div class="p-4">
                <div class="mb-2">
                    <img src="{% static 'images/layouts/layout-1.jpg' %}" class="img-fluid img-thumbnail" alt="">
                </div>

                <div class="form-check form-switch mb-3">
                    <input class="form-check-input theme-choice" type="checkbox" id="light-mode-switch" checked>
                    <label class="form-check-label" for="light-mode-switch">Light Mode</label>
                </div>

                <div class="mb-2">
                    <img src="{% static 'images/layouts/layout-2.jpg' %}" class="img-fluid img-thumbnail" alt="">
                </div>
                <div class="form-check form-switch mb-3">
                    <input class="form-check-input theme-choice" type="checkbox" id="dark-mode-switch" data-bsStyle="{% static 'css/bootstrap-dark.min.css' %}" data-appStyle="{% static 'css/app-dark.min.css' %}">
                    <label class="form-check-label" for="dark-mode-switch">Dark Mode</label>
                </div>

                <!-- <div class="mb-2">
                    <img src="{% static 'images/layouts/layout-3.jpg' %}" class="img-fluid img-thumbnail" alt="">
                </div>
                <div class="form-check form-switch mb-5">
                    <input class="form-check-input theme-choice" type="checkbox" id="rtl-mode-switch" data-appStyle="{% static 'css/app-rtl.min.css' %}">
                    <label class="form-check-label" for="rtl-mode-switch">RTL Mode</label>
                </div>
                <div class="mb-2">
                    <img src="{% static 'images/layouts/layout-4.jpg'%}" class="img-thumbnail" alt="layout images">
                </div>
                <div class="form-check form-switch mb-5">
                    <input class="form-check-input theme-choice" type="checkbox" id="dark-rtl-mode-switch">
                    <label class="form-check-label" for="dark-rtl-mode-switch">Dark RTL Mode</label>
                </div> -->

        
            </div>

        </div> <!-- end slimscroll-menu-->
    </div>
    <!-- /Right-bar -->

    <!-- Right bar overlay-->
    <div class="rightbar-overlay"></div>
{% endblock %}

coinginie/templates/partials/sidebar.html
{% load static %} {% block sidebar %}
    <!-- ========== Left Sidebar Start ========== -->
    <div class="vertical-menu">
      <div data-simplebar class="h-100">
        <!--- Sidemenu -->
        <div id="sidebar-menu">
          <!-- Left Menu Start -->
          <ul class="metismenu list-unstyled" id="side-menu">
            <li class="menu-title" key="t-dashbaords">Dashboard</li>
            <li>
              <a href="javascript: void(0);" class="has-arrow waves-effect">
                <i class="bx bx-home-circle"></i>
                <span key="t-layouts">Dashboard</span>
              </a>
              <ul class="sub-menu" aria-expanded="true">
                <li><a href="{% url 'dashboard' %}" >Dashboard</a></li>
                <li><a href="{% url 'dashboard-trade' %}" >MT5 Trader</a></li>
              </ul>
            </li>
            
            <li class="menu-title" key="t-apps">Apps</li>
            <li>
              <a href="javascript: void(0);" class="has-arrow waves-effect">
                <i class="bx bx-user"></i>
                <span key="t-layouts">Account Apps</span>
              </a>
              <ul class="sub-menu" aria-expanded="true">
                <li><a href="{% url 'users:detail' user.username %}" >My Profile</a></li>
                <li><a href="{% url 'users:profile' %}" >Update Profile</a></li>
                {% if not request.user.is_verified %}
                <li><a href="{% url 'users:kyc' %}" >Get Verified</a></li>
                {% endif %}
                <li><a href="{% url 'users:privacy' %}" >Privacy Settings</a></li>
                {% if user.subscription.subcontract.active == False %}
                <li><a href="{% url 'users:plans' %}" >Subscriptions</a></li>
                {% endif %}
                {% if request.user.is_superuser %}
                <li><a href="{% url 'wallet:transactions' %}" >Verify Transactions</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
        </div>
        <!-- Sidebar -->
      </div>
    </div>
    <!-- Left Sidebar End -->
{% endblock %}