coinginie/users/urls.py
from django.urls import path

from coinginie.users.views import (
    PrivacyPolicyUpdate,
    SubscribePlans,
    UserBankUpdate,
    UserDocUpdate,
    UserUpdateView,
    close_account,
    kyc_verification,
    subscribe,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~subscription/contract/<int:pk>/", view=subscribe, name="subscribe"),
    path("~close/<str:username>/", view=close_account, name="close_account"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~contracts/", view=SubscribePlans.as_view(), name="plans"),
    path("~bank/", view=UserBankUpdate.as_view(), name="account"),
    path("~privacy/", view=PrivacyPolicyUpdate.as_view(), name="privacy"),
    path("~doc/", view=UserDocUpdate.as_view(), name="doc"),
    path("~update/", view=UserUpdateView.as_view(), name="profile"),
    path("~kyc/", view=kyc_verification, name="kyc"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

coinginie/wallet/urls.py
from django.urls import path

from .views import (
    InvestView,
    WithdrawView,
    all_transactions,
    verify_deposit,
    verify_withdraw,
)

app_name = "wallet"
urlpatterns = [
    path("~transactions/", view=all_transactions, name="transactions"),
    path("~invest/confirm/<int:id>/", view=verify_deposit, name="invest_verify"),
    path("~invest/", view=InvestView.as_view(), name="invest"),
    path("~withdraw/confirm/<int:id>/", view=verify_withdraw, name="withdraw_verify"),
    path("~withdraw/", view=WithdrawView.as_view(), name="withdraw"),
]

config/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.flatpages import views as flatpage_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views import defaults as default_views
from django.views.generic import TemplateView
from filebrowser.sites import site as filebrowser

from coinginie.core.views import (
    DashboardTradeView,
    DashboardView,
    MyPasswordChangeView,
    MyPasswordSetView,
)
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("complete-investment/", TemplateView.as_view(template_name="pages/complete.html"), name="comp-inv"),
    path("dashboard/", DashboardView.as_view(),name='dashboard'),
    path("dashboard/MT5/", DashboardTradeView.as_view(),name='dashboard-trade'),

    # Django Admin, use {% url 'admin:index' %}
    # path('jet/', include('jet.urls', namespace='jet')),
    # path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard')),
    path(_("admin/"), include("admin_honeypot.urls", namespace="admin_honeypot")),
    path(_(settings.ADMIN_URL), admin.site.urls),
    path(_(settings.ADMIN_DOC_URL), include("django.contrib.admindocs.urls")),
    path(_(settings.ADMIN_FILEBROWSER_URL), filebrowser.urls),


    # User management
    path("users/", include("coinginie.users.urls", namespace="users")),
    path("wallet/", include("coinginie.wallet.urls", namespace="wallet")),
    path("accounts/", include("allauth.urls")),


    # Your stuff: custom urls includes go here
    path('auth-logout/',TemplateView.as_view(template_name="account/logout-success.html"),name ='pages-logout'),
    path('auth-lockscreen/',TemplateView.as_view(template_name="account/lock-screen.html"),name ='pages_lockscreen'),
    #Custum change password done page redirect
    path('accounts/password/change/', login_required(MyPasswordChangeView.as_view()), name="account_change_password"),
    #Custum set password done page redirect
    path('accounts/password/set/', login_required(MyPasswordSetView.as_view()), name="account_set_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# flatpages
if flatpage_views:
    urlpatterns += [
        path(_("terms/"), flatpage_views.flatpage, {"url":"/terms/"}, name="terms"),
        path(_("cookies/"), flatpage_views.flatpage, {"url":"/cookies/"}, name="cookies"),
        path(_("privacy/"), flatpage_views.flatpage, {"url":"/privacy/"}, name="privacy"),
    ]


# Translation urls
urlpatterns += [
    # path('rosetta/', include('rosetta.urls')),
    path('upload/', include('django_file_form.urls')),
    path('tinymce/', include('tinymce.urls')),
    # Language switcher support urls for django
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += [
    path("sitemap.xml/", sitemap, kwargs={"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

admin.site.site_header = "Dashboard - Ginie Nodes"
admin.site.site_title = "Ginie Nodes DB"
admin.site.index_title = "Ginie Nodes DB"

coinginie/core/models.py
from django.db import models

# Create your models here.

coinginie/wallet/forms.py
from allauth.account.forms import (
    ChangePasswordForm,
    LoginForm,
    ResetPasswordForm,
    ResetPasswordKeyForm,
    SetPasswordForm,
    SignupForm,
)
from crispy_forms.helper import FormHelper
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _

from .models import Deposit, Withdraw

User = get_user_model()


class WithdrawForm(forms.ModelForm):
    class Meta:
        model = Withdraw
        fields = [
            "currency",
            "address",
            "amount",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['currency'].widget = forms.RadioSelect(attrs={'class': 'form-control'})
        self.fields['address'].widget = forms.TextInput(attrs={'class': 'form-control mb-1','placeholder':'Address','id':'autocomplete_input'})
        self.fields['amount'].widget = forms.NumberInput(attrs={'class': 'form-control mb-1','placeholder':'Wallet Address'})

        
class InvestForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = [
            "currency",
            "amount",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['currency'].widget = forms.RadioSelect(attrs={'class': 'form-control'})
        self.fields['amount'].widget = forms.NumberInput(attrs={'class': 'form-control'})

coinginie/contracts/views.py
from django.shortcuts import render

# Create your views here.

coinginie/core/views.py
from allauth.account.views import PasswordChangeView, PasswordSetView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import request
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.base import TemplateView

from coinginie.wallet.models import Transactions


# Create your views here.
class DashboardView(LoginRequiredMixin,View):
    def get(self,request):
        greeting = {}
        greeting['heading'] = "Dashboard" 
        greeting['pageview'] = "Dashboards"
        greeting['transactions'] = Transactions.objects.filter(user=request.user).order_by("-created")[:10]
        greeting['deposits'] = Transactions.objects.filter(user=request.user, type="Invest").order_by("-created")[:10]
        greeting['withdrawals'] = Transactions.objects.filter(user=request.user, type="Withdraw").order_by("-created")[:10]
        return render (request,'dashboard/dashboard-crypto.html',greeting)

class DashboardTradeView(LoginRequiredMixin,View):
    def get(self,request):
        greeting = {}
        greeting['heading'] = "MT5 Trade View" 
        greeting['pageview'] = "MT5 Trade View"
        return render (request,'dashboard/dashboard-trade.html',greeting)

class MyPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy('dashboard')
    
class MyPasswordSetView(LoginRequiredMixin, PasswordSetView):
    success_url = reverse_lazy('dashboard')

coinginie/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from formtools.preview import FormPreview

from coinginie.contracts.models import Contract, Plans, Subscription
from coinginie.users.forms import (
    AccountSettingsForm,
    DocFileForm,
    InvestorForm,
    PrivacyPoliciesForm,
)
from coinginie.users.models import AccountSettings, Investor, PrivacyPolicies
from coinginie.wallet.models import Deposit, Transactions
from coinginie.wallet.tasks import send_admin_mail, send_deposit_mail

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['bankform'] = self.third_form_class(self.request.POST or None, instance=self.request.user.account)
        # context['imageform'] = self.fourth_form_class(self.request.POST or None, self.request.FILES, instance=self.request.user.userprofile)
        context['transactions'] = Transactions.objects.filter(user=self.request.user) 
        context['heading'] = "Profile" 
        context['pageview'] = "Profile"
        return context

user_detail_view = UserDetailView.as_view()

class UserBankUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = AccountSettings
    form_class = AccountSettingsForm
    success_message = "Bank Information successfully updated"

    def get_success_url(self):
        return reverse("users:profile")

    def get_object(self):
        return self.request.user.account

class UserDocUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Investor
    form_class = DocFileForm
    success_message = "Documents successfully updated"

    def get_success_url(self):
        return reverse("users:profile")

    def get_object(self):
        return self.request.user.investor

# def  file_upload(request):
#     if request.method == "POST":
#         doc = request.FILES.get('file')
#         Investor.objects.filter(user=request.user).update(doc=doc)
#         return HttpResponse('')
#     return JsonResponse({'post':'false'})
    
class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Investor
    template_name = "users/profile.html"
    form_class = InvestorForm
    # third_form_class = AccountSettingsForm
    # fourth_form_class = DocFileForm
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user.investor
    
    def form_valid(self, form):
        form.save()
        User.objects.filter(username=self.request.user.username).update(profile_updated=True)   
        return super().form_valid(form)
       
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['bankform'] = self.third_form_class(self.request.POST or None, instance=self.request.user.account)
        # context['docform'] = self.fourth_form_class(self.request.POST or None, self.request.FILES, instance=self.get_object())
        context['heading'] = "Update Profile" 
        context['pageview'] = "Update Profile"
        return context


user_update_view = UserUpdateView.as_view()

@login_required
def kyc_verification(request):
    if request.method == 'POST':
        bankform = AccountSettingsForm(request.POST or None, instance=request.user.account)
        docform = DocFileForm(request.POST or None, request.FILES, instance=request.user.investor)

        if bankform.is_valid() and docform.is_valid():
            bankform.save()
            docform.save()
            
            to_email = request.user.email
            subject = "[GinieNodes] User Verification"
            body = f"""
            Dear {request.user.first_name},
            
            Your request to be verified is being processed.
            
            Please be patient
            
            Yours Truly
            Ginie Nodes
            """
            send_deposit_mail.delay(to_email, subject, body)

# ---------------------------------------------------------------------------

            admin_subject = "[User Verification Request] Admin Notice"
            admin_body = f"""
            {request.user.username} has requested to be verified.
            
            Confirm the information provided.
            
            Then verify them if they meet requirements.
            """
            admins = settings.ADMINS

            send_admin_mail.delay(admins, admin_subject, admin_body)

            # User.objects.filter(username=request.user.username).update(is_verified=True)
            return redirect(request.user.get_absolute_url())
    else:
        bankform = AccountSettingsForm()
        docform = DocFileForm()   
        
            
    return render(request, 'users/kyc.html', {'bankform':bankform,"docform":docform, "heading":"KYC Verification", "pageview":"KYC Verification"})
        
class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class PrivacyPolicyUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = PrivacyPolicies
    template_name = "users/privacy.html"
    form_class = PrivacyPoliciesForm
    success_message = _("Privacy Settings successfully updated")
    
    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user.userprivacypolicy
    
    # def form_valid(self, form):
    #     form.save()
    #     return self.get_success_url()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = "Privacy Settings" 
        context['pageview'] = "Privacy Settings"
        return context


def subscribe(request, pk):
    contract = get_object_or_404(Plans, pk=pk)
    if request.user.subscription:
        Subscription.objects.filter(user=request.user).update(contract=contract)
        return redirect(request.user.get_absolute_url())


class SubscribePlans(LoginRequiredMixin, ListView):
    model = Plans
    template_name = "users/plans.html"
    context_object_name = "objects"
    queryset = Plans.objects.all().order_by('created')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = "Contracts" 
        context['pageview'] = "Contracts"
        return context
    
    
@login_required
def close_account(request, username):
    if not request.user:
        return reverse_lazy("home")
    
    user = get_object_or_404(User, username=username)
    User.objects.filter(username=user.username, is_active=True).update(is_active=False)
    messages.info(request, "Successfully Closed Account")
    return reverse_lazy('home')

coinginie/templates/users/admin.html
{% extends 'partials/base.html' %}
{% load static %}


{% block extra_css %}
<!-- Responsive Table css -->
<link href="{% static 'libs/admin-resources/rwd-table/rwd-table.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block contents %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Investments</h4>
                <p class="card-title-desc">Verify transactions by accepting or deleting a transaction.</p>

                <div class="table-rep-plugin">
                    <div class="table-responsive mb-0" data-pattern="priority-columns">
                        <table id="tech-companies-1" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Transact Type</th>
                                    <th data-priority="1">Date</th>
                                    <th data-priority="3">Currency</th>
                                    <th data-priority="3">Amount</th>
                                    <th data-priority="3">Investor</th>
                                    <th data-priority="3">Status</th>
                                    <th data-priority="3">Accept</th>
                                    <th data-priority="3">Reject</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for obj in objects %}
                                <tr>
                                    <th><span class="text-success}">INVESTMENT.</span></th>
                                    <td>{{obj.created|date:"d M, Y"}}</td>
                                    <td>{{obj.currency}}</td>
                                    <td>${{obj.amount}}</td>
                                    <td>{{obj.user}}</td>
                                    <td>{% if obj.verified == True %}Verified{% else %}Unverified{% endif %}</td>
                                    <td><a href="{% url 'wallet:invest_verify' obj.id %}">Accept Investment</a></td>
                                    <td><a href="">Reject Transaction</a></td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <th colspan="7">No Transactions</th>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div> <!-- end col -->

    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Withdrawals</h4>
                <p class="card-title-desc">Verify transactions by accepting or deleting a transaction.</p>

                <div class="table-rep-plugin">
                    <div class="table-responsive mb-0" data-pattern="priority-columns">
                        <table id="tech-companies-1" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Transact Type</th>
                                    <th data-priority="1">Date</th>
                                    <th data-priority="3">Currency</th>
                                    <th data-priority="3">Amount</th>
                                    <th data-priority="3">Investor</th>
                                    <th data-priority="3">Status</th>
                                    <th data-priority="3">Accept</th>
                                    <th data-priority="3">Reject</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for obj in withdrawals %}
                                <tr>
                                    <th><span class="text-danger}">WITHDRAWAL.</span></th>
                                    <td>{{obj.created|date:"d M, Y"}}</td>
                                    <td>{{obj.currency}}</td>
                                    <td>${{obj.amount}}</td>
                                    <td>{{obj.user}}</td>
                                    <td>{% if obj.verified == True %}Verified{% else %}Unverified{% endif %}</td>
                                    <td><a href="{% url 'wallet:withdraw_verify' obj.id %}">Accept Withdrawal</a></td>
                                    <td><a href="">Reject Transaction</a></td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <th colspan="7">No Transactions</th>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->
{% endblock %}
{% block extra_javascript %}
<!-- Responsive Table js -->
<script src="{% static 'libs/admin-resources/rwd-table/rwd-table.min.js' %}"></script>

<!-- Init js -->
<script src="{% static 'js/pages/table-responsive.init.js' %}"></script>

{% endblock %}

coinginie/templates/users/kyc.html
{% extends 'partials/base.html' %}
{% load static crispy_forms_tags %}

{% block extra_css %}
<!-- Plugins css -->
<link href="{% static 'libs/dropzone/dist/min/dropzone.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}


{% block contents %}
<div class="row justify-content-center mt-lg-5">
    <div class="col-xl-5 col-sm-8">
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <div class="row justify-content-center">
                        <div class="col-lg-10">
                            <h4 class="mt-4 fw-semibold">Update Profile</h4>
                            <p class="text-muted mt-3">Fill in personal information and update your photo here.</p>

                            <div class="mt-4">
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#verificationModal">
                                    Update Profile Information
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="row justify-content-center mt-5 mb-2">
                        <div class="col-sm-6 col-8">
                            <div>
                                <img src="{% static 'images/verification-img.png'%}" alt="" class="img-fluid">
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="verificationModal" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Verify your Account</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form method="post" action="{% url 'users:kyc' %}" id="form" name="form" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div id="kyc-verify-wizard">
                                        <!-- Personal Info -->
                                        <h3>Bank Info</h3>
                                        <section>
                                            <div>
                                                <div class="row">
                                                    {{bankform|crispy}}
                                                    <!-- <div class="col-lg-6">
                                                        <div class="mb-3">
                                                            <label for="kycfirstname-input" class="form-label">First name</label>
                                                            <input type="text" class="form-control" id="kycfirstname-input" placeholder="Enter First name">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6">
                                                        <div class="mb-3">
                                                            <label for="kyclastname-input" class="form-label">Last name</label>
                                                            <input type="text" class="form-control" id="kyclastname-input" placeholder="Enter Last name">
                                                        </div>
                                                    </div> -->
                                                </div>
                                                
                                            </div>
                                        </section>

                                        <h3>Upload Valid Documents</h3>
                                        <section>
                                            <div>
                                                <div class="row">
                                                    {{docform|crispy}}
                                                    <!-- <div class="col-lg-6">
                                                        <div class="mb-3">
                                                            <label for="kycfirstname-input" class="form-label">First name</label>
                                                            <input type="text" class="form-control" id="kycfirstname-input" placeholder="Enter First name">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6">
                                                        <div class="mb-3">
                                                            <label for="kyclastname-input" class="form-label">Last name</label>
                                                            <input type="text" class="form-control" id="kyclastname-input" placeholder="Enter Last name">
                                                        </div>
                                                    </div> -->
                                                </div>
                                                
                                            </div>
                                        </section>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
{% endblock %}

{% block extra_javascript %}

        <!-- jquery step -->
        <script src="{% static 'libs/jquery-steps/build/jquery.steps.min.js' %}"></script>

        <script src="{% static 'libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js'%}"></script>

        <!-- dropzone js -->
        <script src="{% static 'libs/dropzone/dist/min/dropzone.min.js' %}"></script>

        <!-- init js -->
        <script src="{% static 'js/pages/crypto-kyc-app.init.js' %}"></script>

        <script>
            //var form = document.getElementById('kyc-verify-wizard');
            
            //document.getElementBySelectorAll('a[href="#finish"]').addEventListener('click', function() {
              //  form.submit();
            //})
            //$(function () {
            //    $('#kyc-verify-wizard').step('a[href$="#finish"]').console.log("fixhed button");
            //})
            //$('#kyc-verify-wizard .actions div:last-child').append('<button type="submit" id="submit" class="button">Finish</button>');
            //document.getElementById('finish').submit();

            //$(function () {
            //    $('#kyc-verify-wizard')({
            //        transitionEffect: "slideLeft",
            //        onFinished: function (event, currentIndex) {
            //            $('#form"]').submit();
            //    })
            //})
        </script>
{% endblock %}

coinginie/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}